import type {Metadata} from "next";
import "./globals.css";

import {Montserrat} from "next/font/google"
import {ThemeProvider} from "@/components/theme-provider";

const montserrat = Montserrat({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${montserrat.className} antialiased p-4 md:px-16 md:py-8`}
    >
    <ThemeProvider attribute={"class"} defaultTheme={"dark"} enableColorScheme enableSystem>
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
